--- #YAML:1.0
name:                Text-Template-Library
version:             0.03
abstract:            a derived class of Text::Template
license:             ~
author:              
    - Torsten Foertsch <torsten.foertsch@gmx.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Member:                 1.6
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
